os:
 - windows
 - linux
 - osx
language: node_js
node_js:
  - lts/*
  - node
git:
  depth: 1
cache: yarn

env:
  - COMMAND=build
  - COMMAND=test:ci
  - COMMAND=test:integration:ci

script: yarn ${COMMAND}
